server.port=8080

spring.mvc.cors.allowed-origins=http://localhost:5179,http://localhost:5178
spring.mvc.cors.allowed-methods=*
spring.mvc.cors.allowed-headers=*

logging.level.org.springframework.web=DEBUG
logging.level.cinema=DEBUG