server.port=8080
sspring.mvc.cors.allowed-origins=http://localhost:5179
spring.mvc.cors.allowed-methods=*
spring.mvc.cors.allowed-headers=*
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
# W??cz pe?ne logi
logging.level.cinema=DEBUG
# CORS Configuration
#spring.mvc.cors.allow-credentials=true